# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fitnest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fitnest
    pod 'Alamofire'

  target 'FitnestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitnestUITests' do
    # Pods for testing
  end

end
